### ISSUE TITLE
error with UPDATE_ADDONS_PATH

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/install-odoo#102]
it has comma at the end of generated list, which lead to adding ``/`` to addons-path

**Comment by iledarn** [comment]
@yelizariev ,
fixed here:
https://github.com/it-projects-llc/install-odoo/pull/103
https://github.com/it-projects-llc/install-odoo/pull/104
https://github.com/it-projects-llc/install-odoo/pull/105
