### ISSUE TITLE
GIT_PULL doesn't work in 11.0

### ISSUE THREAD

**Issue by yelizariev** [it-projects-llc/install-odoo#130]
`su: must be run from a terminal
`

**Comment by iledarn** [comment]
`docker exec -u odoo -i -t odoo /bin/bash -c "export GIT_PULL='yes'; bash /install-odoo-saas.sh"`

should be

`docker exec -u root -i -t odoo /bin/bash -c "export GIT_PULL='yes'; bash /install-odoo-saas.sh"`

fixed it in 8.0
