### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by ljseals** [it-projects-llc/install-odoo#85]
yaml
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python-dateutil
E: Unable to locate package python-decorator
E: Unable to locate package python-docutils
E: Unable to locate package python-feedparser
E: Unable to locate package python-imaging
E: Unable to locate package python-jinja2
E: Unable to locate package python-ldap
E: Unable to locate package python-libxslt1
E: Unable to locate package python-lxml
E: Unable to locate package python-mako
E: Unable to locate package python-mock
E: Unable to locate package python-openid
E: Unable to locate package python-passlib
E: Unable to locate package python-psutil
E: Unable to locate package python-psycopg2
E: Unable to locate package python-pybabel
E: Unable to locate package python-pychart
E: Unable to locate package python-pydot
E: Unable to locate package python-pyparsing
E: Unable to locate package python-pypdf
E: Unable to locate package python-reportlab
E: Unable to locate package python-suds
E: Unable to locate package python-tz
E: Unable to locate package python-vatnumber
E: Unable to locate package python-vobject
E: Unable to locate package python-werkzeug
E: Unable to locate package python-xlwt

**Comment by rcastro-tyc** [comment]
@ljseals  I solved it running  again 
`apt-get update`
`apt-get upgrade -y`

Regards,

**Comment by ljseals** [comment]
Thanks!
