### ISSUE TITLE
Failing for odoo 9.0

### ISSUE THREAD

**Issue by augustynr** [it-projects-llc/install-odoo#9]
Hi,
Thank you for the script. I am running it on clean ubuntu 14.04.

I have run your script for version 9.0 or odoo and run into couple problems.
First compilation of the cryptography fails with error:
Failed building wheel for cffi
  Running setup.py clean for cffi
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/9b/f4/2e/d03e949a551719a1ffcb659f2c63d8444f4df12e994ce52112
Successfully built pysftp pycparser
Failed to build cryptography cffi

Then following does not exist:
git clone -b 9.0 https://github.com/xpansa/hr.git xpansa/hr/

Any idea how to fix it?
btw: I am running this script as root 
I can provide full log of the install.

**Comment by augustynr** [comment]
it looks like these 2 are required to solve the first issue:
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev

**Comment by yelizariev** [comment]
@iledarn

**Comment by iledarn** [comment]
memo:
 * add into the script:
pip install simplejson

**Comment by iledarn** [comment]
memo:
 * there is no 9.0 branch in the https://github.com/xpansa/hr.git xpansa/hr/

**Comment by elliotxin** [comment]
for this script"install-odoo-saas.sh", before run this, should i already install odoo9 or , just run it in the fresh ubuntu 14? thanks a lot.

**Comment by yelizariev** [comment]
@elliotxin you don't need odoo 9 installled before running script. Use it on a fresh ubuntu
