### ISSUE TITLE
No module named telebot.apihelper

### ISSUE THREAD

**Issue by gridworkz** [it-projects-llc/install-odoo#93]
Hi Ivan:

I'm running a VirtualBox Ubuntu 16.04.2 from osboxes.org. For Xenial I did a manual install of wkhtmltopdf' before running install-odoo-sass.sh (as root): 

 - apt-get install libxrender1 fontconfig xvfb xfonts-base xfonts-75dpi libjpeg62-turbo
 - wget https://downloads.wkhtmltopdf.org/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz -P /tmp/
 - cd /opt/
 - tar xf /tmp/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
 - ln -s /opt/wkhtmltox/bin/wkhtmltopdf /usr/bin/wkhtmltopdf

and the install went through fine. I did however move the curl fetch of pip to the correct location like you did in your fix.

OK, so the install seemed to go fine. Then I executed:

sudo su - odoo -s /bin/bash -c "/usr/local/src/odoo-source/odoo-bin -c /etc/openerp-server.conf

Where do go in my browser? - just http://localhost?

When I go to localhost it throws an Internal Server 500 error and the console says:

.....

ImportError: No module named telebot.apihelper

.....

I think the pyTelegramBotAPI didn't get installed - if I install it via apt-get, then the 'emoji' module can't be found, then orm etc.. Did I miss a  step or did is something missing in the script? 

BTW: When I do:'sudo -u odoo psql odoo.example.com' there is no database found as well.

Cheers,
Dave

**Comment by yelizariev** [comment]
It was fixed in https://github.com/it-projects-llc/odoo-telegram, which I added to repo list in the script recently
